<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//============================================================+
// Nama Berkas : mencetak_program_kerja_kepala_laboratorium.php
// Lokasi      : application/views/guru/
// Author      : Selamet Hanafi
//               selamethanafi@yahoo.co.id
//
// (c) Copyright:
//               Selamet Hanafi
//               sianis.web.id
//               selamet.hanafi@gmail.com
//
// License:
//    Copyright (C) 2014 Selamet Hanafi
//    Informasi detil ada di LISENSI.TXT 
//============================================================+
?>
<?php
$this->fpdf->FPDF("P","cm","A4");
$this->fpdf->SetMargins(2,2,2);		
$this->fpdf->AliasNbPages();
$this->fpdf->SetTitle("Dupak Sebelum 2014");
$this->fpdf->SetAuthor("Selamet Hanafi");
$this->fpdf->SetSubject("Sistem Informasi Madrasah");
$this->fpdf->SetKeywords("sistem, informasi, madrasah");
// Cell(lebar, tinggi, teks, bingkai, ganti baris, perataan, fill, mixed link)
$this->fpdf->AddPage();
$golongan = preg_replace("/_/","/", $golongan);
$versi = $datamasa['versi'];
$awal = $datamasa['awal'];
$akhir_penilaian = '2013-12-31';
$awal_penilaian = $datamasa['awal_penilaian'];
$tmt = $datamasa['tmt'];
$tahun = $datamasa['tahun'];
$bulan = $datamasa['bulan'];
$tahun_baru = $datamasa['tahun_baru'];
$bulan_baru = $datamasa['bulan_baru'];
$t = 0.4;
$x = 2;
$l = 18;
$this->fpdf->SetX($x+10);
$this->fpdf->setFont('Helvetica','',8);
$this->fpdf->cell(3,$t,'Lampiran I',0,0,'L',0);
$this->fpdf->cell(3,$t,': Keputusan Menteri Pendidikan',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(3,$t,'',0,0,'C',0);
$this->fpdf->cell(3,$t,'  dan Kebudayaan',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(3,$t,'',0,0,'C',0);
$this->fpdf->cell(2,$t,'  Nomor',0,0,'L',0);
$this->fpdf->cell(3,$t,': 025/O/1995',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(3,$t,'',0,0,'C',0);
$this->fpdf->cell(2,$t,'  Tanggal',0,0,'L',0);
$this->fpdf->cell(3,$t,': 8 Maret 1995',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','',10);
$this->fpdf->cell(3,$t,'',0,2,'C',0);
$this->fpdf->cell($l,$t,'DAFTAR USUL PENETAPAN ANGKA KREDIT',0,2,'C',0);
$this->fpdf->cell($l,$t,'JABATAN GURU',0,2,'C',0);
$this->fpdf->cell($l,$t,'Masa Penilaian : '.date_to_long_string($awal_penilaian).' s.d '.date_to_long_string($akhir_penilaian),0,2,'C',0);
$k1 = 1;
$k2 = 6;
$k3 = 2;
$k4 = 9;
$t = 0.6;
$t2 = 0.4;
$this->fpdf->setFont('Helvetica','',9);
$this->fpdf->SetX($x);
$this->fpdf->cell(3,$t,'',0,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($l,$t,'KETERANGAN PERORANGAN',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'1',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Nama',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$dataguru['nama'],1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'2',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'NIP / Nomor Seri Karpeg',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$dataguru['nip'].' / '.$dataguru['karpeg'],1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'3',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Tempat dan Tanggal Lahir',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$dataguru['tempat'].', '.date_to_long_string($dataguru['tanggallahir']),1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'4',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Jenis Kelamin',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.ubahjenkel($dataguru['jenkel']),1,2,'L',0);
$this->fpdf->SetX($x);
$yy = $this->fpdf->GetY();
$this->fpdf->cell($k1,$t2,'5',0,0,'C',0);
$this->fpdf->Cell($k2+$k3,0.4,'Pendidikan yang telah diperhitungkan',0,0,'L',0);
$this->fpdf->cell($k4,$t2,': '.$datapaklama['pendidikan'],0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t2,' ',0,0,'L',0);
$this->fpdf->Cell($k2+$k3,$t2,'angka kreditnya',0,0,'L',0);
$this->fpdf->cell($k4,$t2,' ',0,2,'L',0);
$this->fpdf->SetXY($x,$yy);
$this->fpdf->cell($k1,$t2+$t2,' ',1,0,'L',0);
$this->fpdf->Cell($k2+$k3,$t2+$t2,'',1,0,'L',0);
$this->fpdf->Cell($k4,$t2+$t2,' ',1,2,'L',0);

$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'6',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Pangkat / Gol. Ruang / TMT',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$datapaklama['pangkat'].' / '.$datapaklama['golongan'].' / '.tanggal($datapaklama['tmt']),1,2,'L',0);
$y3 = $this->fpdf->GetY();
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'7',0,0,'C',0);
$this->fpdf->cell($k2,$t,'Masa kerja Golongan',0,0,'L',0);
$this->fpdf->cell($k3,$t,'Lama',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$datapaklama['tahun'].' tahun '.$datapaklama['bulan'].' bulan',1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'L',0);
$this->fpdf->cell($k3,$t,'Baru',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$datamasa['tahun_baru'].' tahun '.$datamasa['bulan_baru'].' bulan',1,2,'L',0);
$this->fpdf->SetXY($x,$y3);
$this->fpdf->cell($k1,$t+$t,'',1,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',1,2,'C',0);

$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'8',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Jenis guru',1,0,'L',0);
$this->fpdf->cell($k4,$t,': GURU MATA PELAJARAN',1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'9',1,0,'C',0);
$this->fpdf->cell($k2+$k3,$t,'Tugas',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$datapaklama['tugas'],1,2,'L',0);
$y3 = $this->fpdf->GetY();
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'10',0,0,'C',0);
$this->fpdf->cell($k2,$t,'Alamat',0,0,'L',0);
$this->fpdf->cell($k3,$t,'Sekolah',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$this->config->item('sek_alamat'),1,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'L',0);
$this->fpdf->cell($k3,$t,'Rumah',1,0,'L',0);
$this->fpdf->cell($k4,$t,': '.$dataguru['alamat'],1,2,'L',0);
$this->fpdf->SetXY($x,$y3);
$this->fpdf->cell($k1,$t+$t,'',1,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',1,2,'C',0);

$k1 = 1.5;
$k2 = 0.5;
$k3 = 1;
$k4 = 5;
$k5 = 1;
$k6 = 1.5;
$k7 = 1.5;
$k8 = 1.5;
$k9 = 1.5;
$k10 = 1.5;
$k11 = 1.5;
$t = 0.4;
$this->fpdf->cell($k1,$t,'',0,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($l,$t,'UNSUR YANG DINILAI',0,2,'L',0);
$this->fpdf->SetX($x);
$yy = $this->fpdf->GetY();
$this->fpdf->cell($k1,3*$t,'NOMOR',1,0,'C',0);
$this->fpdf->SetXY($x+$k1,$yy);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,3*$t,'UNSUR UTAMA DAN SUB UNSUR UTAMA',1,0,'C',0);
$this->fpdf->SetXY($x+$k1+$k2+$k3+$k4+$k5+$k6,$yy);
$this->fpdf->cell($k7+$k8+$k9+$k10+$k11,$t,'ANGKA KREDIT MENURUT',1,2,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7+$k8+$k9,$t,'SEKOLAH PENGUSUL
',1,0,'C',0);
$this->fpdf->cell($k10+$k11,$t,'TIM PENILAI',1,2,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7,$t,'LAMA',1,0,'C',0);
$this->fpdf->cell($k8,$t,'BARU',1,0,'C',0);
$this->fpdf->cell($k9,$t,'JUMLAH',1,0,'C',0);
$this->fpdf->cell($k10,$t,'LAMA',1,0,'C',0);
$this->fpdf->cell($k11,$t,'BARU',1,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'1',1,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'2',1,0,'C',0);
$this->fpdf->cell($k10,$t,'3',1,0,'C',0);
$this->fpdf->cell($k11,$t,'4',1,0,'C',0);

$this->fpdf->cell($k9,$t,'5',1,0,'C',0);
$this->fpdf->cell($k10,$t,'6',1,0,'C',0);
$this->fpdf->cell($k11,$t,'7',1,2,'C',0);
$yy = $this->fpdf->GetY();
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Berdasarkan PAK '.$golongans.' per '.tanggal($datapaklama['tmt']),0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Nomor '.$datapaklama['nomor'],0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7,$t,$datapaklama['ak'],0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$datapaklama['ak'],0,2,'C',0);
$ak_total = $datapaklama['ak'];
$ak_sub_a = $datapaklama['ak'];
$this->fpdf->SetX($x);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','B',9);
$this->fpdf->cell($k1,$t,'I.',0,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Pendidikan',0,2,'L',0);
$this->fpdf->setFont('Helvetica','',9);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2,$t,'1.',0,0,'L',0);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'Pendidikan Sekolah memperoleh gelar/ijazah',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2);
$this->fpdf->cell($k3,$t,'1.1.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'.....',0,2,'L',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2,$t,'2.',0,0,'L',0);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'Mengikuti Pendidikan dan Pelatihan',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2);
$this->fpdf->cell($k3,$t,'2.1.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Pendidikan dan Pelatihan ...',0,2,'L',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);

$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'Jumlah Sub unsur Pendidikan (A)',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_a,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_a,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,2,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','B',9);
$this->fpdf->cell($k1,$t,'II.',0,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Proses Belajar Mengajar (PBM)',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','',9);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.1.',0,0,'L',0);
//cacah semester
$nsemester = 0;
$ak_sub_b = 0;
foreach($tmasa->result() as $dm)
{
	$nsemester = $nsemester + $dm->semester;
}
$ak = $this->dupak->ak(1,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$ak_sub_b = $ak_sub_b + $akt;
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan Penyusunan Program',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'Pengajaran/praktik '.$nsemester.' semester',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4);
$this->fpdf->cell($k5,$t,$nsemester.' x '.$ak,0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7);
$this->fpdf->cell($k8,$t,$akt,0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$akt,0,2,'C',0);

$ak = $this->dupak->ak(2,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$ak_sub_b = $ak_sub_b + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.2.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan Penyajian Program',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'Pengajaran/praktik '.$nsemester.' semester',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4);
$this->fpdf->cell($k5,$t,$nsemester.' x '.$ak,0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7);
$this->fpdf->cell($k8,$t,$akt,0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$akt,0,2,'C',0);

$ak = $this->dupak->ak(3,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$ak_sub_b = $ak_sub_b + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.3.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan Evaluasi Belajar/',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'praktik '.$nsemester.' semester',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4);
$this->fpdf->cell($k5,$t,$nsemester.' x '.$ak,0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7);
$this->fpdf->cell($k8,$t,$akt,0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$akt,0,2,'C',0);

$ak = $this->dupak->ak(4,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$ak_sub_b = $ak_sub_b + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.4.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan Analisis hasil evaluasi',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'belajar/praktik '.$nsemester.' semester',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4);
$this->fpdf->cell($k5,$t,$nsemester.' x '.$ak,0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7);
$this->fpdf->cell($k8,$t,$akt,0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$akt,0,2,'C',0);

$ak = $this->dupak->ak(5,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$ak_sub_b = $ak_sub_b + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.5.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan dalam penyusunan dan 
',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'pelaksanaan program perbaikan dan',0,2,'L',0);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'pengayaan '.$nsemester.' semester',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4);
$this->fpdf->cell($k5,$t,$nsemester.' x '.$ak,0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7);
$this->fpdf->cell($k8,$t,$akt,0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,$akt,0,2,'C',0);
$yy1 = $this->fpdf->GetY();
$selisih = $yy1 - $yy;
$this->fpdf->SetXY($x,$yy);
$this->fpdf->Cell($k1,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k2+$k3+$k4+$k5+$k6,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k7,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k8,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k9,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k10,$selisih,'',1,0,'L',0);
$this->fpdf->Cell($k11,$selisih,'',1,2,'L',0);

$this->fpdf->AddPage();
$yy = $this->fpdf->GetY();
$this->fpdf->cell($k1,3*$t,'NOMOR',1,0,'C',0);
$this->fpdf->SetXY($x+$k1,$yy);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,3*$t,'UNSUR UTAMA DAN SUB UNSUR UTAMA',1,0,'C',0);
$this->fpdf->SetXY($x+$k1+$k2+$k3+$k4+$k5+$k6,$yy);
$this->fpdf->cell($k7+$k8+$k9+$k10+$k11,$t,'ANGKA KREDIT MENURUT',1,2,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7+$k8+$k9,$t,'SEKOLAH PENGUSUL
',1,0,'C',0);
$this->fpdf->cell($k10+$k11,$t,'TIM PENILAI',1,2,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7,$t,'LAMA',1,0,'C',0);
$this->fpdf->cell($k8,$t,'BARU',1,0,'C',0);
$this->fpdf->cell($k9,$t,'JUMLAH',1,0,'C',0);
$this->fpdf->cell($k10,$t,'LAMA',1,0,'C',0);
$this->fpdf->cell($k11,$t,'BARU',1,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'1',1,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'2',1,0,'C',0);
$this->fpdf->cell($k10,$t,'3',1,0,'C',0);
$this->fpdf->cell($k11,$t,'4',1,0,'C',0);
$this->fpdf->cell($k9,$t,'5',1,0,'C',0);
$this->fpdf->cell($k10,$t,'6',1,0,'C',0);
$this->fpdf->cell($k11,$t,'7',1,2,'C',0);
$ak = $this->dupak->ak(6,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.6.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Melaksanakan dalam penyusunan dan pelaksanaan',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'program bimbingan dan konseling di kelas yang',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'menjadi tanggung jawabnya (khusus guru kelas)',0,2,'L',0);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'',0,2,'L',0);
$ak = $this->dupak->ak(7,$golongan);
$akt = $nsemester * $ak;
$ak_total = $ak_total + $akt;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t,'1.7.',0,0,'L',0);
$this->fpdf->cell($k4+$k5+$k6,$t,'Membimbing siswa dalam kegiatan',0,2,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'ekstrakurikuler',0,2,'L',0);
$this->fpdf->cell($k3+$k4+$k5+$k6,$t,'',0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'Jumlah Subunsur PBM (B)',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_b,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_b,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,2,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','B',9);
$this->fpdf->cell($k1,$t+$t,'III.',0,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+$t,'Pengembangan Profesi',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','',9);
$this->fpdf->cell($k1,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t+$t,'1.1.',0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'Jumlah Subunsur Pengembangan Profesi (C)',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,2,'C',0);

$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'JUMLAH UNSUR UTAMA (A) + (B) + (C)',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_b,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,$ak_sub_b,1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k7,$t+0.3,'',1,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'C',0);
$this->fpdf->cell(16.5,$t+$t,'UNSUR PENUNJANG',1,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,0.2,'',0,2,'L',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Berdasarkan PAK .................... per ...............',0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t,'Nomor ....................',0,0,'L',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6);
$this->fpdf->cell($k7,$t,'',0,0,'C',0);
$this->fpdf->SetX($x+$k1+$k2+$k3+$k4+$k5+$k6+$k7+$k8);
$this->fpdf->cell($k9,$t,'',0,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','B',9);
$this->fpdf->cell($k1,$t+$t,'IV.',0,0,'C',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+$t,'Penunjang Proses Belajar',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->setFont('Helvetica','',9);
$this->fpdf->cell($k1,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t+$t,'1.1.',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t+$t,'1.2.',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k2,$t+$t,'',0,0,'C',0);
$this->fpdf->cell($k3,$t+$t,'1.3.',0,2,'L',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'JUMLAH UNSUR PENUNJANG',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k8,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k9,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k10,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k11,$t+0.3,'',1,2,'C',0);
$this->fpdf->SetX($x+$k1);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$t+0.3,'JUMLAH UNSUR UTAMA DAN UNSUR PENUNJANG',1,0,'R',0);
$this->fpdf->cell($k7,$t+0.3,$datapaklama['ak'],1,0,'C',0);
$this->fpdf->cell($k8,$t+0.3,$ak_total,1,0,'C',0);
$this->fpdf->cell($k9,$t+0.3,$ak_total,1,0,'C',0);
$this->fpdf->cell($k10,$t+0.3,'',1,0,'C',0);
$this->fpdf->cell($k11,$t+0.3,'',1,2,'C',0);
$yy1 = $this->fpdf->GetY();
$selisih = $yy1 - $yy;
$this->fpdf->SetXY($x,$yy);
$this->fpdf->cell($k1,$selisih,'',1,0,'R',0);
$this->fpdf->cell($k2+$k3+$k4+$k5+$k6,$selisih,'',1,0,'R',0);
$this->fpdf->cell($k7,$selisih,'',1,0,'R',0);
$this->fpdf->cell($k8,$selisih,'',1,0,'R',0);
$this->fpdf->cell($k9,$selisih,'',1,0,'C',0);
$this->fpdf->cell($k10,$selisih,'',1,0,'C',0);
$this->fpdf->cell($k11,$selisih,'',1,2,'C',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'Bahan yang dinilai',0,2,'L',0);
$k2 = 4;
$k3 = 0.5;
$k4 = 2;
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'1.',0,0,'R',0);
$this->fpdf->cell($k2,$t,'Pendidikan',0,0,'L',0);
$this->fpdf->cell($k3,$t,':',0,0,'L',0);
$this->fpdf->cell($k4,$t,'0.000',0,2,'R',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'2.',0,0,'R',0);
$this->fpdf->cell($k2,$t,'PBM',0,0,'L',0);
$this->fpdf->cell($k3,$t,':',0,0,'L',0);
$this->fpdf->cell($k4,$t,$ak_sub_b,0,2,'R',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'3.',0,0,'R',0);
$this->fpdf->cell($k2,$t,'Pengembangan profesi',0,0,'L',0);
$this->fpdf->cell($k3,$t,':',0,0,'L',0);
$this->fpdf->cell($k4,$t,'0.000',0,2,'R',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'4.',0,0,'R',0);
$this->fpdf->cell($k2,$t,'Unsur penunjang',0,0,'L',0);
$this->fpdf->cell($k3,$t,':',0,0,'L',0);
$this->fpdf->cell($k4,$t,'0.000',0,2,'R',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t,'',0,0,'R',0);
$this->fpdf->cell($k2,$t,'Jumlah   ',0,0,'R',0);
$this->fpdf->cell($k3,$t,':',0,0,'L',0);
$this->fpdf->cell($k4,$t,$ak_sub_b,0,2,'R',0);
$this->fpdf->SetX($x);
$this->fpdf->cell($k1,$t*2,'',0,0,'R',0);
$this->fpdf->SetX($x+12);
$this->fpdf->cell(6,$t,$this->config->item('lokasi').', 31 Desember 2013',0,2,'L',0);
$this->fpdf->SetX($x+12);
$this->fpdf->cell(6,$t,'Kepala '.$this->config->item('sek_nama'),0,2,'L',0);
$this->fpdf->SetX($x+12);
$this->fpdf->cell(6,$t*3,'',0,2,'L',0);
$namakepala = cari_kepala('2013/2014','1');
$nipkepala = cari_nip_kepala('2013/2014','1');
$this->fpdf->SetX($x+12);
$this->fpdf->cell(6,$t,$namakepala,0,2,'L',0);
$this->fpdf->SetX($x+12);
$this->fpdf->cell(6,$t,'NIP '.$nipkepala,0,2,'L',0);
$this->fpdf->cell(6,$t,'',0,2,'L',0);
$this->fpdf->AddPage();
$yy = $this->fpdf->GetY();
$this->fpdf->SetX($x);
$this->fpdf->cell(10,$t*2,'',0,2,'L',0);
$this->fpdf->cell(10,$t,'PENDAPAT TIM PENILAI',0,2,'L',0);
$this->fpdf->cell(10,$t*2,'',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'...................., .....................',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'Ketua TIM Penilai...',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t*3,'',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'______________________________',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'NIP ',0,2,'L',0);
$this->fpdf->cell(10,$t*2,'',0,2,'L',0);
$this->fpdf->SetX($x);
$this->fpdf->cell(10,$t,'PERSETUJUAN : ....................................................',0,2,'L',0);
$this->fpdf->cell(10,$t*2,'',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,$this->config->item('lokasi').', .....................',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'Kepala '.$this->config->item('sek_nama'),0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t*3,'',0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,$namakepala,0,2,'L',0);
$this->fpdf->SetX($x+10);
$this->fpdf->cell(7,$t,'NIP '.$nipkepala,0,2,'L',0);
$yy1 = $this->fpdf->GetY();
$selisih = $yy1-$yy+$t+$t;
$this->fpdf->SetXY($x,$yy);
$this->fpdf->cell(17.5,$selisih,'',1,2,'L',0);
$ta = $this->db->query("select * from `dupak_dupak_lama` where `username`='$nim'");
if($ta->num_rows() == 0)
{
	$this->db->query("insert into `dupak_dupak_lama` (`username`,`ak_pbm`) values ('$nim','$ak_sub_b')");
}
$this->db->query("update `dupak_dupak_lama` set `ak_pbm` = '$ak_sub_b' where `username`='$nim'");

$this->fpdf->Output('dupak_guru_'.$golongan.'_'.$nim.'.pdf',"I");
